--- #YAML:1.0
name:               Lingua-EN-Tagger
version:            0.21
abstract:           Part-of-speech tagger for English natural language processing.
author:
    - Maciej Ceglowski and Aaron Coburn <maciej@ceglowski.com>, <aaron@coburncuadrado.com>
license:            gpl_3
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Spec:          0.84
    HTML::Parser:        3.45
    HTML::Tagset:        3.20
    Lingua::Stem:        0.81
    Memoize:             1.01
    Memoize::ExpireLRU:  0.55
    perl:                5.008001
    Storable:            2.10
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
